// Generated by gencpp from file plutodrone/PlutoPilot.msg
// DO NOT EDIT!


#ifndef PLUTODRONE_MESSAGE_PLUTOPILOT_H
#define PLUTODRONE_MESSAGE_PLUTOPILOT_H

#include <ros/service_traits.h>


#include <plutodrone/PlutoPilotRequest.h>
#include <plutodrone/PlutoPilotResponse.h>


namespace plutodrone
{

struct PlutoPilot
{

typedef PlutoPilotRequest Request;
typedef PlutoPilotResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PlutoPilot
} // namespace plutodrone


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::plutodrone::PlutoPilot > {
  static const char* value()
  {
    return "a9cb76ac323ce16acce1b8357e8cbb55";
  }

  static const char* value(const ::plutodrone::PlutoPilot&) { return value(); }
};

template<>
struct DataType< ::plutodrone::PlutoPilot > {
  static const char* value()
  {
    return "plutodrone/PlutoPilot";
  }

  static const char* value(const ::plutodrone::PlutoPilot&) { return value(); }
};


// service_traits::MD5Sum< ::plutodrone::PlutoPilotRequest> should match 
// service_traits::MD5Sum< ::plutodrone::PlutoPilot > 
template<>
struct MD5Sum< ::plutodrone::PlutoPilotRequest>
{
  static const char* value()
  {
    return MD5Sum< ::plutodrone::PlutoPilot >::value();
  }
  static const char* value(const ::plutodrone::PlutoPilotRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::plutodrone::PlutoPilotRequest> should match 
// service_traits::DataType< ::plutodrone::PlutoPilot > 
template<>
struct DataType< ::plutodrone::PlutoPilotRequest>
{
  static const char* value()
  {
    return DataType< ::plutodrone::PlutoPilot >::value();
  }
  static const char* value(const ::plutodrone::PlutoPilotRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::plutodrone::PlutoPilotResponse> should match 
// service_traits::MD5Sum< ::plutodrone::PlutoPilot > 
template<>
struct MD5Sum< ::plutodrone::PlutoPilotResponse>
{
  static const char* value()
  {
    return MD5Sum< ::plutodrone::PlutoPilot >::value();
  }
  static const char* value(const ::plutodrone::PlutoPilotResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::plutodrone::PlutoPilotResponse> should match 
// service_traits::DataType< ::plutodrone::PlutoPilot > 
template<>
struct DataType< ::plutodrone::PlutoPilotResponse>
{
  static const char* value()
  {
    return DataType< ::plutodrone::PlutoPilot >::value();
  }
  static const char* value(const ::plutodrone::PlutoPilotResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLUTODRONE_MESSAGE_PLUTOPILOT_H
